version: '2'

services:
  camunda:
    build:
      context: ./camunda-bpm-wildfly
      args:
        - MANAGEMENT_USERNAME=demo
        - MANAGEMENT_PASSWORD=demo
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - camundadb
    networks:
      - camunda
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - WAIT_FOR=camundadb:5432
      - DB_URL=jdbc:postgresql://camundadb:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - DB_CONN_MAXACTIVE=20
      - DB_CONN_MINIDLE=5
  camundadb:
    build: ./postgres-camunda-bpm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - $PWD/:/var/lib/postgresql
    networks:
      - camunda

  docker_compose_ui:
    image: francescou/docker-compose-ui:1.3.0
    container_name: docker_compose_ui
    hostname: docker_compose_ui
    ports:
        - 5000:5000
    working_dir: /opt/docker-compose-projects/
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - .:/opt/docker-compose-projects/camunda-bpm-platform
    networks:
      - tools

networks:
  camunda:
  tools:
